# Generated by Django 3.1 on 2020-10-18 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='wind_direction',
            field=models.CharField(max_length=30),
        ),
    ]
