# Generated by Django 3.1 on 2020-10-18 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0002_auto_20201018_1601'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='humidity',
            field=models.DecimalField(decimal_places=4, max_digits=7),
        ),
        migrations.AlterField(
            model_name='city',
            name='temp',
            field=models.DecimalField(decimal_places=4, max_digits=7),
        ),
        migrations.AlterField(
            model_name='city',
            name='wind_speed',
            field=models.DecimalField(decimal_places=4, max_digits=7),
        ),
    ]
