# Generated by Django 3.1 on 2020-10-20 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0006_auto_20201019_2101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='powerplant',
            name='co2',
            field=models.DecimalField(decimal_places=5, max_digits=10),
        ),
        migrations.AlterField(
            model_name='powerplant',
            name='hg',
            field=models.DecimalField(decimal_places=5, max_digits=10),
        ),
        migrations.AlterField(
            model_name='powerplant',
            name='nox',
            field=models.DecimalField(decimal_places=5, max_digits=10),
        ),
        migrations.AlterField(
            model_name='powerplant',
            name='so_2',
            field=models.DecimalField(decimal_places=5, max_digits=10),
        ),
    ]
