# Generated by Django 3.1.1 on 2020-12-05 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0007_auto_20201019_2122'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('state', models.CharField(max_length=30)),
                ('lat', models.CharField(max_length=30)),
                ('long', models.CharField(max_length=30)),
                ('date', models.CharField(max_length=30)),
                ('regmark', models.CharField(max_length=30)),
                ('temp', models.DecimalField(decimal_places=2, max_digits=7)),
                ('humidity', models.DecimalField(decimal_places=4, max_digits=7)),
                ('wind_speed', models.DecimalField(decimal_places=4, max_digits=7)),
                ('wind_direction', models.CharField(max_length=30)),
                ('speed', models.DecimalField(decimal_places=6, max_digits=7)),
                ('accuracy', models.DecimalField(decimal_places=6, max_digits=7)),
                ('c_co', models.DecimalField(decimal_places=6, max_digits=7)),
                ('c_co2', models.DecimalField(decimal_places=6, max_digits=7)),
                ('c_hc', models.DecimalField(decimal_places=6, max_digits=7)),
                ('c_no', models.DecimalField(decimal_places=6, max_digits=7)),
                ('efco', models.DecimalField(decimal_places=6, max_digits=7)),
                ('efhc', models.DecimalField(decimal_places=6, max_digits=7)),
                ('efno', models.DecimalField(decimal_places=6, max_digits=7)),
            ],
            options={
                'verbose_name_plural': 'books',
            },
        ),
        migrations.DeleteModel(
            name='City',
        ),
        migrations.DeleteModel(
            name='PowerPlant',
        ),
        migrations.DeleteModel(
            name='Vehicle',
        ),
    ]
