# Generated by Django 3.1.1 on 2020-12-05 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0008_auto_20201205_1518'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='date',
            new_name='author',
        ),
        migrations.RenameField(
            model_name='book',
            old_name='lat',
            new_name='places_to_purchase',
        ),
        migrations.RenameField(
            model_name='book',
            old_name='long',
            new_name='title',
        ),
        migrations.RemoveField(
            model_name='book',
            name='accuracy',
        ),
        migrations.RemoveField(
            model_name='book',
            name='c_co',
        ),
        migrations.RemoveField(
            model_name='book',
            name='c_co2',
        ),
        migrations.RemoveField(
            model_name='book',
            name='c_hc',
        ),
        migrations.RemoveField(
            model_name='book',
            name='c_no',
        ),
        migrations.RemoveField(
            model_name='book',
            name='efco',
        ),
        migrations.RemoveField(
            model_name='book',
            name='efhc',
        ),
        migrations.RemoveField(
            model_name='book',
            name='efno',
        ),
        migrations.RemoveField(
            model_name='book',
            name='humidity',
        ),
        migrations.RemoveField(
            model_name='book',
            name='name',
        ),
        migrations.RemoveField(
            model_name='book',
            name='regmark',
        ),
        migrations.RemoveField(
            model_name='book',
            name='speed',
        ),
        migrations.RemoveField(
            model_name='book',
            name='state',
        ),
        migrations.RemoveField(
            model_name='book',
            name='temp',
        ),
        migrations.RemoveField(
            model_name='book',
            name='wind_direction',
        ),
        migrations.RemoveField(
            model_name='book',
            name='wind_speed',
        ),
        migrations.AddField(
            model_name='book',
            name='lowest_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=8),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='book',
            name='published_date',
            field=models.CharField(default=0.01935483870967742, max_length=8),
            preserve_default=False,
        ),
    ]
