# Generated by Django 3.1.1 on 2020-12-05 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0010_auto_20201205_1536'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='lowest_price',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
        migrations.AlterField(
            model_name='book',
            name='published_date',
            field=models.CharField(max_length=10),
        ),
    ]
