# Generated by Django 3.1.1 on 2020-12-05 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0011_auto_20201205_1537'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='places_to_purchase',
            field=models.CharField(max_length=50),
        ),
    ]
