# Generated by Django 3.1.1 on 2020-12-06 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0012_auto_20201205_1538'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='general_review',
            field=models.CharField(default=1, max_length=300),
            preserve_default=False,
        ),
    ]
