# Generated by Django 3.1.4 on 2020-12-06 05:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0017_book_personal_reviews'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='personal_reviews',
        ),
    ]
