# Generated by Django 3.1 on 2020-09-27 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0003_remove_file_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='edited',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
