# Generated by Django 3.1 on 2020-09-27 01:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0004_topic_edited'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topic',
            name='edited',
        ),
    ]
