# Generated by Django 3.1 on 2020-09-27 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0005_remove_topic_edited'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='edited',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
