# Generated by Django 3.1.1 on 2020-12-06 02:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0007_auto_20200926_2022'),
    ]

    operations = [
        migrations.DeleteModel(
            name='File',
        ),
    ]
